import {randomBytes,randomUUID} from 'node:crypto';
import {readFile} from 'node:fs/promises';
import {Pool} from 'pg';
import {afterAll,beforeAll,describe,expect,it,vi} from 'vitest';
import {ActionAccess} from '../src/hosted/action-access.js';
import {GoogleConnections,type GoogleConfig} from '../src/hosted/google.js';
import {runAction} from '../src/hosted/action-runner.js';
import {ConnectionStore,type ConnectionProvider} from '../src/hosted/connections.js';
import {createHostedServer} from '../src/hosted/server.js';
import {createHostedDatabase} from '../src/hosted/db.js';
import type {GithubConfig} from '../src/hosted/github.js';
import {loadHostedConfig} from '../src/hosted/config.js';
import type {AuthenticatedContext} from '../src/hosted/identity.js';
const databaseUrl=process.env.CAPYKIT_TEST_POSTGRES_URL;
describe.skipIf(!databaseUrl)('connector actions with real PostgreSQL authority',()=>{
 const schema=`actions_${randomUUID().replaceAll('-','')}`,role=`${schema}_runtime`;
 const admin=new Pool({connectionString:databaseUrl});const scoped=new URL(databaseUrl??'postgres://localhost/test');scoped.searchParams.set('options',`-c search_path=${schema},public`);
 const db=new Pool({connectionString:scoped.toString()});const runtimeUrl=new URL(scoped);runtimeUrl.searchParams.set('options',`-c search_path=${schema},public -c role=${role}`);
 const runtime=new Pool({connectionString:runtimeUrl.toString()}),access=new ActionAccess(runtime);
 const googleConfig:GoogleConfig={clientId:'fixture.apps.googleusercontent.com',clientSecret:randomBytes(32).toString('hex'),encryptionKey:randomBytes(32),keyVersion:'test',callbackUrl:'https://capykit.example.test/v1/connections/google/callback'};
 const provider={authorizationUrl:(state:string)=>`https://accounts.google.com/?state=${state}`,exchange:vi.fn(()=>Promise.resolve({refreshToken:randomBytes(32).toString('hex'),subject:'123',email:'drive@example.test'})),refresh:vi.fn(()=>Promise.resolve(randomBytes(32).toString('hex')))};
 const drive=new GoogleConnections(runtime,provider,googleConfig),connections=new ConnectionStore(runtime);
 const expiresAt=()=>new Date(Date.now()+86400000).toISOString();
 let owner:AuthenticatedContext,member:AuthenticatedContext,other:AuthenticatedContext;
 const identities=new Map<string,AuthenticatedContext>();
 const app=createHostedServer({database:createHostedDatabase(runtimeUrl.toString()),config:loadHostedConfig({DATABASE_URL:runtimeUrl.toString(),CAPYKIT_PUBLIC_BASE_URL:'https://capykit.example.test',CAPYKIT_AUTH_URL:'http://auth:9999'}),googleConfig,googleProvider:provider as never,auth:{verifyBearer:token=>Promise.resolve(identities.get(token)?.identity),requestOtp:async()=>{},verifyOtp:()=>Promise.resolve(undefined),refresh:()=>Promise.resolve(undefined),signOut:async()=>{}}});
 async function actor(workspaceId:string=randomUUID(),roleName:'owner'|'member'='owner'):Promise<AuthenticatedContext>{await db.query("insert into workspaces(id,slug,name) values($1,$2,'Fixture') on conflict do nothing",[workspaceId,workspaceId]);const id=randomUUID(),subject=randomUUID();await db.query("insert into principals(id,workspace_id,kind,display_name) values($1,$2,'human','Fixture')",[id,workspaceId]);await db.query('insert into workspace_memberships(workspace_id,principal_id,role) values($1,$2,$3)',[workspaceId,id,roleName]);await db.query("insert into identity_bindings(principal_id,provider,provider_subject,email,verified_at) values($1,'gotrue',$2,'fixture@example.test',now())",[id,subject]);return {identity:{provider:'gotrue',subject,email:'fixture@example.test'},membership:{workspaceId,principalId:id,principalKind:'human',role:roleName,active:true}};}
 async function connect(context:AuthenticatedContext){const start=await drive.start(context,'session');await drive.callback(context,'session',{state:new URL(start.authorizationUrl).searchParams.get('state')??'',code:'fixture'});}
 async function agent(){const issued=await access.issueKey(owner,{name:'Assistant',expiresAt:expiresAt()});const context=await access.authenticate(issued.key);if(!context)throw new Error('Missing fixture agent');return {issued,context};}
 const grant=(context:AuthenticatedContext,actionId='drive.get-file.v1')=>access.grant(owner,{recipientId:context.membership.principalId,actionId,connectionId:owner.membership.workspaceId,expiresAt:expiresAt()});
 beforeAll(async()=>{await admin.query(`create schema ${schema}`);for(const file of ['001_hosted_workspace_identity.sql','002_hosted_database_access.sql','003_hosted_capabilities.sql','004_hosted_connections.sql','005_hosted_grants.sql','006_hosted_app_connections.sql','008_connector_actions.sql','009_personal_app_connections.sql'])await db.query((await readFile(new URL(`../scripts/migrations/${file}`,import.meta.url),'utf8')).replaceAll('capykit_runtime',role));owner=await actor();member=await actor(owner.membership.workspaceId,'member');other=await actor();identities.set('owner',owner);identities.set('member',member);await connect(owner);await connect(other);});
 afterAll(async()=>{vi.unstubAllGlobals();await app.close();await runtime.end();await db.end();await admin.query(`drop schema ${schema} cascade;drop role ${role}`);await admin.end();});
 it('discovers no actions before a grant and never persists plaintext keys or exposes credentials',async()=>{const {issued,context}=await agent();expect((await access.catalog(context)).actions).toEqual([]);expect((await app.inject({url:'/v1/actions',headers:{authorization:`Bearer ${issued.key}`}})).json()).toEqual({actions:[]});expect(JSON.stringify((await db.query('select * from agent_credentials')).rows)).not.toContain(issued.key);expect(JSON.stringify(await access.options(owner))).not.toMatch(/key_hash|refresh_token/);expect((await runtime.query('select * from agent_credentials')).rowCount).toBe(0);await expect(access.issueKey(member,{name:'Bad',expiresAt:expiresAt()})).rejects.toMatchObject({code:'FORBIDDEN'});await expect(access.grant(other,{recipientId:context.membership.principalId,actionId:'drive.get-file.v1',connectionId:owner.membership.workspaceId,expiresAt:expiresAt()})).rejects.toMatchObject({code:'NOT_FOUND'});});
 it('uses one recorded grant, never switches after revocation, and rejects expired/mutated scope',async()=>{const {context}=await agent();const g=await grant(context);await grant(context);const bound=await access.bind(context,'drive.get-file.v1',owner.membership.workspaceId);expect(bound.grantId).toBe(g.id);await access.revokeGrant(owner,g.id??'');await expect(access.check(context,bound)).rejects.toMatchObject({code:'FORBIDDEN'});await expect(runtime.query('update connector_action_grants set generation=2')).rejects.toMatchObject({code:'42501'});await expect(grant(context,'custom_api_call')).rejects.toMatchObject({code:'NOT_FOUND'});});
 it('executes through the same browser/agent API and rechecks authority before delivering results',async()=>{const {issued,context}=await agent();const g=await grant(context);vi.stubGlobal('fetch',vi.fn(()=>Promise.resolve(new Response(JSON.stringify({id:'file_1',name:'Report',mimeType:'application/pdf',owners:['private']})))));
  const result=await app.inject({method:'POST',url:'/v1/actions/drive.get-file.v1/run',headers:{authorization:`Bearer ${issued.key}`},payload:{connectionId:owner.membership.workspaceId,input:{fileId:'file_1'}}});expect(result.statusCode).toBe(200);expect(result.json()).toEqual({result:{id:'file_1',name:'Report',mimeType:'application/pdf'}});
  const browser=await app.inject({method:'POST',url:'/v1/actions/drive.get-file.v1/run',headers:{origin:'https://capykit.example.test',cookie:'capykit_session=owner; capykit_csrf=safe','x-csrf-token':'safe'},payload:{connectionId:owner.membership.workspaceId,input:{fileId:'file_1'}}});expect(browser.statusCode).toBe(200);
  vi.stubGlobal('fetch',vi.fn(async()=>{await access.revokeGrant(owner,g.id??'');return new Response(JSON.stringify({id:'file_1',name:'private withheld',mimeType:'text/plain'}));}));await expect(runAction(access,connections,drive,context,'drive.get-file.v1',owner.membership.workspaceId,{fileId:'file_1'})).rejects.toMatchObject({code:'FORBIDDEN'});
  vi.unstubAllGlobals();});
 it('checks search query restrictions, real bounded paging and cross-workspace guesses',async()=>{const {context}=await agent();await grant(context,'drive.find-files.v1');const fetcher=vi.fn((url:unknown)=>{const query=new URL(String(url));expect(query.searchParams.get('pageSize')).toBe('25');expect(query.searchParams.get('q')).toBe("name contains 'Budget' and trashed = false");expect(query.searchParams.get('pageToken')).toBe('page_2');return Promise.resolve(new Response(JSON.stringify({files:[{id:'file_1',name:'Budget',mimeType:'text/plain'}],nextPageToken:'page_3'})));});vi.stubGlobal('fetch',fetcher);expect(await runAction(access,connections,drive,context,'drive.find-files.v1',owner.membership.workspaceId,{name:'Budget',pageToken:'page_2'})).toEqual({result:{files:[{id:'file_1',name:'Budget',mimeType:'text/plain'}],nextPageToken:'page_3'}});expect(fetcher).toHaveBeenCalledOnce();await expect(access.bind(context,'drive.find-files.v1',other.membership.workspaceId)).rejects.toMatchObject({code:'NOT_FOUND'});vi.unstubAllGlobals();});
 it('scopes GitHub actions to granted immutable repositories and revokes tokens after response denial',async()=>{
  const id=randomUUID();await db.query("insert into provider_connections(workspace_id,id,status,installation_id,account,created_by_principal_id,consent_by_principal_id,consent_at) values($1,$2,'active','999','{\"login\":\"fixture\"}',$3,$3,now())",[owner.membership.workspaceId,id,owner.membership.principalId]);
  for(const repositoryId of ['101','102'])await db.query('insert into connection_repositories values($1,$2,$3,$4,$5)',[owner.membership.workspaceId,id,repositoryId,`fixture/repo-${repositoryId}`,`https://github.com/fixture/repo-${repositoryId}`]);
  const {context}=await agent();const grant=await access.grant(owner,{recipientId:context.membership.principalId,actionId:'github.get-issue.v1',connectionId:id,repositoryIds:['101'],expiresAt:expiresAt()});
  const mintedToken=randomBytes(32).toString('hex');const githubProvider={mint:vi.fn(()=>Promise.resolve({token:mintedToken,expiresAt:new Date(Date.now()+3500000).toISOString()})),revokeInstallationToken:vi.fn(()=>Promise.resolve())} as unknown as ConnectionProvider;
  const githubConfig:GithubConfig={appId:'1',appSlug:'fixture',clientId:'fixture',clientSecret:'fixture',privateKey:'unused',webhookSecret:'fixture',encryptionKey:randomBytes(32),keyVersion:'v1',callbackUrl:'https://capykit.example.test/v1/connections/github/callback'};
  const store=new ConnectionStore(runtime,githubProvider,githubConfig);const fetcher=vi.fn((url:unknown)=>Promise.resolve(new Response(JSON.stringify(String(url).includes('/repositories/')?{id:101,full_name:'fixture/renamed-repo'}:{number:1,title:'Issue',state:'open',body:'private excluded'}))));vi.stubGlobal('fetch',fetcher);
  expect(await runAction(access,store,drive,context,'github.get-issue.v1',id,{repositoryId:'101',issueNumber:1})).toEqual({result:{number:1,title:'Issue',state:'open'}});
  expect(githubProvider.mint).toHaveBeenCalledWith('999',['101']);expect(githubProvider.revokeInstallationToken).toHaveBeenCalledWith(mintedToken);
  const calls=fetcher.mock.calls.length;await expect(runAction(access,store,drive,context,'github.get-issue.v1',id,{repositoryId:'102',issueNumber:1})).rejects.toMatchObject({code:'FORBIDDEN'});expect(fetcher.mock.calls).toHaveLength(calls);
  fetcher.mockImplementationOnce(async()=>{await access.revokeGrant(owner,grant.id??'');return new Response(JSON.stringify({id:101,full_name:'fixture/renamed-repo'}));});await expect(runAction(access,store,drive,context,'github.get-issue.v1',id,{repositoryId:'101',issueNumber:1})).rejects.toMatchObject({code:'FORBIDDEN'});expect(githubProvider.revokeInstallationToken).toHaveBeenCalledTimes(2);vi.unstubAllGlobals();
 });
 it('uses current roles for discovery and fences an owner run after demotion without switching grants',async()=>{
  const temporaryOwner=await actor();await connect(temporaryOwner);
  const bound=await access.bind(temporaryOwner,'drive.get-file.v1',temporaryOwner.membership.workspaceId);
  await access.grant(temporaryOwner,{recipientId:temporaryOwner.membership.principalId,actionId:'drive.find-files.v1',connectionId:temporaryOwner.membership.workspaceId,expiresAt:expiresAt()});
  await db.query("update workspace_memberships set role='member' where principal_id=$1",[temporaryOwner.membership.principalId]);
  expect((await access.catalog(temporaryOwner)).actions.map(a=>a.id)).toEqual(['drive.find-files.v1']);
  await expect(access.bind(temporaryOwner,'drive.get-file.v1',temporaryOwner.membership.workspaceId)).rejects.toMatchObject({code:'FORBIDDEN'});
  await expect(access.check(temporaryOwner,bound)).rejects.toMatchObject({code:'FORBIDDEN'});
 });
 it('fences connection replacement, key rotation/revocation, membership changes and missing CSRF',async()=>{const {issued,context}=await agent();await grant(context);const bound=await access.bind(context,'drive.get-file.v1',owner.membership.workspaceId);const replacement=await access.issueKey(owner,{rotateKeyId:issued.id,expiresAt:expiresAt()});expect(await access.authenticate(issued.key)).toBeUndefined();await expect(access.check(context,bound)).rejects.toMatchObject({code:'MEMBERSHIP_INACTIVE'});const current=await access.authenticate(replacement.key);expect(current).toBeDefined();await access.revokeKey(owner,replacement.id??'');expect(await access.authenticate(replacement.key)).toBeUndefined();expect((await app.inject({method:'POST',url:'/v1/action-grants',headers:{origin:'https://capykit.example.test',cookie:'capykit_session=owner'},payload:{}})).statusCode).toBe(403);
  await grant(member);const memberBound=await access.bind(member,'drive.get-file.v1',owner.membership.workspaceId);await drive.disconnect(owner);await connect(owner);await expect(access.check(member,memberBound)).rejects.toMatchObject({code:'NOT_FOUND'});expect((await access.catalog(member)).actions).toEqual([]);
  const fresh=await agent();await grant(fresh.context);const freshBound=await access.bind(fresh.context,'drive.get-file.v1',owner.membership.workspaceId);await db.query('update workspace_memberships set active=false where principal_id=$1',[fresh.context.membership.principalId]);await expect(access.check(fresh.context,freshBound)).rejects.toMatchObject({code:'MEMBERSHIP_INACTIVE'});
 });
});
