import { describe, expect, it } from "vitest";
import { createHostedApi } from "../src/app/http.js";
import { InMemoryIdentityStore } from "../src/app/identity.js";
const config = { cookieSecret: "test-secret", allowedCallbackOrigins: ["http://localhost:3000"], publicOrigin: "http://localhost:3000", secureCookies: false };
const store = new InMemoryIdentityStore({ principals: [{ workspaceId: "workspace-a", principalId: "owner-a", kind: "human", displayName: "Owner A", active: true }], memberships: [{ workspaceId: "workspace-a", principalId: "owner-a", role: "owner", active: true }] });
describe("hosted API", () => {
  it("reports readiness without leaking configuration values", async () => { const app = await createHostedApi({ config, identityStore: store }); const response = await app.inject({ method: "GET", url: "/health/ready" }); expect(response.json()).toEqual({ status: "degraded", database: "missing", supabase: "missing" }); await app.close(); });
  it("serves /v1/me from the server-side session principal", async () => { const app = await createHostedApi({ config, identityStore: store }); const response = await app.inject({ method: "GET", url: "/v1/me", cookies: { capykit_session: "owner-a" } }); expect(response.statusCode).toBe(200); expect(response.json()).toMatchObject({ workspace: { id: "workspace-a" }, principal: { id: "owner-a", kind: "human" }, membership: { role: "owner" } }); await app.close(); });
  it("rejects cookie-authenticated mutations without CSRF and unknown callback origins", async () => { const app = await createHostedApi({ config, identityStore: store }); const missingCsrf = await app.inject({ method: "POST", url: "/v1/auth/logout", cookies: { capykit_session: "owner-a" } }); expect(missingCsrf.statusCode).toBe(403); const badOrigin = await app.inject({ method: "GET", url: "/health/live", headers: { origin: "https://evil.example" } }); expect(badOrigin.statusCode).toBe(403); const okLogout = await app.inject({ method: "POST", url: "/v1/auth/logout", cookies: { capykit_csrf: "token" }, headers: { "x-csrf-token": "token" } }); expect(okLogout.statusCode).toBe(200); await app.close(); });
  it("gives generic OTP responses", async () => { const app = await createHostedApi({ config, identityStore: store }); const response = await app.inject({ method: "POST", url: "/v1/auth/otp", headers: { "content-type": "application/json", "x-csrf-token": "token" }, cookies: { capykit_csrf: "token" }, payload: { email: "unknown@example.com" } }); expect(response.statusCode).toBe(202); expect(response.json()).toEqual({ status: "if_invited_email_was_sent" }); await app.close(); });
});
