import {randomBytes} from 'node:crypto';
import {afterEach,expect,it,vi} from 'vitest';
import {PieceEngine,type PieceMetadata} from '../src/hosted/piece-engine.js';
const piece:PieceMetadata={name:'@activepieces/piece-text-helper',version:'0.6.6',auth:null,actions:{concat:{name:'concat',displayName:'Concat',props:{}}}};
function fixture(){const paths:string[]=[];const requests:Record<string,unknown>[]=[];const engine=new PieceEngine({baseUrl:'http://engine.invalid',email:'engine@example.invalid',password:randomBytes(24).toString('hex'),encryptionKey:randomBytes(32).toString('base64'),oauthClients:{}});
 vi.stubGlobal('fetch',vi.fn((input:unknown,init:RequestInit)=>{const path=new URL(String(input)).pathname;paths.push(path);const body=typeof init.body==='string'?JSON.parse(init.body) as Record<string,unknown>:{};requests.push(body);
  if(init.method==='DELETE')return Promise.resolve(new Response(null,{status:204}));
  const response=path.endsWith('sign-in')?{token:randomBytes(24).toString('hex'),projectId:'private-project'}:path==='/api/v1/flows'?{id:'private-flow',status:'DISABLED',version:{trigger:{name:'trigger'}}}:path.endsWith('/private-flow')?{id:'private-flow',status:'DISABLED',version:{id:'private-version',trigger:{nextAction:{settings:{pieceVersion:'0.6.6'}}}}}:path.endsWith('test-step')?{id:'private-run'}:{status:'SUCCEEDED',steps:{capykit_action:{output:'Hello Capykit'}}};return Promise.resolve(new Response(JSON.stringify(response),{headers:{'content-type':'application/json'}}));
 }));return {engine,paths,requests};}
afterEach(()=>vi.unstubAllGlobals());
it('pins a disabled native draft and checks authority immediately before execution, then deletes it',async()=>{const {engine,paths,requests}=fixture();let authorized=false;const value=await engine.runAction(piece,'concat',{texts:['Hello','Capykit']},'private_connection',()=>{expect(paths.at(-1)).toBe('/api/v1/flows/private-flow');authorized=true;return Promise.resolve();});expect(authorized).toBe(true);expect(value.content[0]?.text).toBe('"Hello Capykit"');const operation=requests[2] as {request:{action:{settings:{pieceVersion:string;input:Record<string,unknown>}}}};expect(operation.request.action.settings.pieceVersion).toBe('0.6.6');expect(operation.request.action.settings.input.auth).toBe("{{connections['private_connection']}}");expect(paths.at(-1)).toBe('/api/v1/flows/private-flow');expect(paths.some(p=>/publish|enable/.test(p))).toBe(false);});
it('does not start an action after revocation during draft creation and still cleans up',async()=>{const {engine,paths}=fixture();await expect(engine.runAction(piece,'concat',{},'private_connection',()=>Promise.reject(new Error('Authority revoked')))).rejects.toThrow('Authority revoked');expect(paths).not.toContain('/api/v1/sample-data/test-step');expect(paths.at(-1)).toBe('/api/v1/flows/private-flow');});
it('accepts upstream204 disconnect responses',async()=>{const {engine}=fixture();await expect(engine.disconnect('private_connection')).resolves.toBeUndefined();});
