import { createHash, randomBytes, randomUUID } from 'node:crypto';
import type { Pool,PoolClient } from 'pg';
import { z } from 'zod';
import { ConnectionError } from './connections.js';
import { authorizeWorkspace } from './workspace-access.js';
import type { AuthenticatedContext } from './identity.js';
import { seal,unseal } from './github.js';
import { PieceEngine,type PieceMetadata } from './piece-engine.js';
import { literalInput,pieceFields } from './piece-properties.js';
function fail(code='INVALID_REQUEST',status=400):never{throw new ConnectionError(code,status);}
const hash=(v:string)=>createHash('sha256').update(v).digest('hex');
const uuid=z.uuid(), actionName=z.string().regex(/^[a-zA-Z0-9_-]{1,120}$/u);
// Only independently reviewed actions can be delegated; arbitrary API calls can forward credentials.
const shareable:Record<string,string[]>={'text-helper':['concat','reverse'],'google-drive':[],'github':[]};
const reviewedVersions:Record<string,string>={'text-helper':'0.6.6','google-drive':'0.11.0','github':'0.9.0'};
const canShare=(id:string,name:string,version:string)=>reviewedVersions[id]===version&&shareable[id]?.includes(name)===true;
function parse<T>(schema:z.ZodType<T>,input:unknown):T{const result=schema.safeParse(input);return result.success?result.data:fail();}
interface Row {workspace_id:string;id:string;owner_principal_id:string;app_id:string;display_name:string;status:string;generation:number;connector_version:string;upstream_id:string|null;external_id:string;setup:unknown;state_hash:string|null;session_hash:string|null;expires_at:Date|null;}
interface Bound {row:Row;grantId:string|null;actionName:string;}
export class PersonalConnections {
 constructor(readonly pool:Pool,readonly engine:PieceEngine|undefined,readonly origin:string){}
 private configured(){return this.engine??fail('CONFIGURATION_UNAVAILABLE',503);}
 private async tx<T>(context:AuthenticatedContext,fn:(client:PoolClient)=>Promise<T>){const client=await this.pool.connect();try{await client.query('begin');await authorizeWorkspace(client,context);const result=await fn(client);await client.query('commit');return result;}catch(error){await client.query('rollback');throw error;}finally{client.release();}}
 private async own(client:PoolClient,context:AuthenticatedContext,id:string){const row=(await client.query<Row>('select * from personal_app_connections where workspace_id=$1 and id=$2 and owner_principal_id=$3 for update',[context.membership.workspaceId,parse(uuid,id),context.membership.principalId])).rows[0];if(!row||context.membership.principalKind!=='human')fail('NOT_FOUND',404);return row;}
 private async audit(client:PoolClient,context:AuthenticatedContext,row:Row,event:string,action:string|null=null,grantId:string|null=null){await client.query('insert into personal_connection_audit(workspace_id,actor_principal_id,connection_id,event,action_name,grant_id) values($1,$2,$3,$4,$5,$6)',[context.membership.workspaceId,context.membership.principalId,row.id,event,action,grantId]);}
 private aad(row:Row){return JSON.stringify(['personal-connection',row.workspace_id,row.owner_principal_id,row.id,row.generation]);}
 private encryption(){return {encryptionKey:Buffer.from(this.configured().config.encryptionKey,'base64'),keyVersion:'personal-v1'};}
 async list(context:AuthenticatedContext){return this.tx(context,async client=>{if(context.membership.principalKind==='human')await client.query("update personal_app_connections set status='reconnect_required',setup=null,state_hash=null,session_hash=null,expires_at=null where workspace_id=$1 and owner_principal_id=$2 and status='pending' and expires_at<now()",[context.membership.workspaceId,context.membership.principalId]);const rows=(await client.query<Row>('select * from personal_app_connections where workspace_id=$1 order by created_at desc limit 200',[context.membership.workspaceId])).rows;return rows.map(row=>({id:row.id,appId:row.app_id,name:row.display_name,status:row.status,personal:row.owner_principal_id===context.membership.principalId,version:row.connector_version}));});}
 async describe(context:AuthenticatedContext,id:string){await this.tx(context,async()=>{});const engine=this.configured(),piece=await engine.metadata(id);
  const auth=piece.auth===null?[]:Array.isArray(piece.auth)?piece.auth:[piece.auth];
  return {appId:id,version:piece.version,methods:auth.length?auth.map((a,index)=>({index,type:String(a.type),name:typeof a.displayName==='string'?a.displayName:'Connection',description:(typeof a.description==='string'?a.description:'').replace(/<[^>]*>/gu,'').slice(0,3000),fields:pieceFields(a.props),...(a.type==='OAUTH2'?{ready:Boolean(engine.config.oauthClients[piece.name]),scopes:Array.isArray(a.scope)?a.scope.filter(s=>typeof s==='string'):[]}: {ready:true})})):[{index:0,type:'NO_AUTH',name:'No account required',description:'Enable this tool for your personal use.',fields:[],ready:true}],actions:Object.entries(piece.actions).map(([name,a])=>({name,displayName:a.displayName,description:a.description??'',shareable:canShare(id,name,piece.version),fields:pieceFields(a.props)}))};
 }
 private async allocate(context:AuthenticatedContext,piece:PieceMetadata,appId:string,name:string,setup:Record<string,unknown>,session:string,state:string):Promise<Row>{return this.tx(context,async client=>{
  if(context.membership.principalKind!=='human')fail('FORBIDDEN',403);
  await client.query('select pg_advisory_xact_lock(hashtextextended($1,148))',[context.membership.workspaceId+':'+context.membership.principalId]);
  const count=(await client.query<{count:string}>("select count(*) from personal_app_connections where workspace_id=$1 and owner_principal_id=$2 and status in ('active','pending') and (expires_at is null or expires_at>now())",[context.membership.workspaceId,context.membership.principalId])).rows[0];if(Number(count?.count)>=80)fail('CONNECTION_LIMIT',409);
  const id=randomUUID(),row={workspace_id:context.membership.workspaceId,owner_principal_id:context.membership.principalId,id,generation:1} as Row;
  const result=(await client.query<Row>(`insert into personal_app_connections(workspace_id,id,owner_principal_id,app_id,connector_version,display_name,external_id,setup,state_hash,session_hash,expires_at) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,now()+interval '10 minutes') returning *`,[row.workspace_id,id,row.owner_principal_id,appId,piece.version,name,'ck_'+id.replaceAll('-',''),seal(this.encryption(),setup,this.aad(row)),hash(state),hash(session)])).rows[0];if(!result)fail();await this.audit(client,context,result,'setup_started');return result;
 });}
 async start(context:AuthenticatedContext,session:string,appId:string,raw:unknown){
  const body=parse(z.object({name:z.string().trim().min(1).max(80),method:z.number().int().min(0).max(20),credentials:z.record(z.string(),z.unknown()).default({})}).strict(),raw);
  const credentials=literalInput(body.credentials),engine=this.configured(),piece=await engine.metadata(appId);
  const auth=piece.auth===null?[{type:'NO_AUTH'}]:Array.isArray(piece.auth)?piece.auth:[piece.auth];const method=auth[body.method];if(!method)fail();const type=String(method.type);
  const fields=pieceFields(method.props);if(fields.some(f=>f.required&&(credentials[f.key]===undefined||credentials[f.key]==='')))fail();
  let value:Record<string,unknown>;let authorization:Awaited<ReturnType<PieceEngine['authorization']>>|undefined;
  if(type==='OAUTH2'){const central=engine.config.oauthClients[piece.name];if(!central)fail('PROVIDER_SETUP_REQUIRED',503);for(const [key,value] of Object.entries(credentials)){if(!central.allowedProps[key]?.includes(value as string|number|boolean))fail();}const callback=this.origin+(engine.config.oauthClients[piece.name]?.callbackPath??'/v1/connections/personal/callback');authorization=await engine.authorization(piece,callback,credentials);value={type:'OAUTH2',props:credentials,redirect_url:callback,scope:authorization.url.searchParams.get('scope')??'',...(authorization.verifier?{code_challenge:authorization.verifier}:{})};}
  else if(type==='SECRET_TEXT')value={type,secret_text:parse(z.string().min(1).max(16000),credentials.secret_text)};
  else if(type==='BASIC_AUTH')value={type,username:parse(z.string().min(1).max(4000),credentials.username),password:parse(z.string().min(1).max(16000),credentials.password)};
  else if(['CUSTOM_AUTH','OIDC'].includes(type))value={type,props:credentials};
  else if(type==='NO_AUTH')value={type};else fail('AUTH_METHOD_UNAVAILABLE',409);
  const state=randomBytes(32).toString('base64url'),row=await this.allocate(context,piece,appId,body.name,value,session,state);
  if(authorization){authorization.url.searchParams.set('state',state);return {connectionId:row.id,authorizationUrl:authorization.url.href};}
  await this.finish(context,row,piece,value);return {connectionId:row.id,status:'connected'};
 }
 private async finish(context:AuthenticatedContext,row:Row,piece:PieceMetadata,value:Record<string,unknown>){const engine=this.configured();let upstreamId:string|undefined;
  try{upstreamId=await engine.connect(piece,row.external_id,row.display_name,value);await this.tx(context,async client=>{const current=await this.own(client,context,row.id);if(current.status!=='pending'||current.generation!==row.generation||!current.expires_at||current.expires_at.getTime()<=Date.now())fail('CONNECT_STATE_INVALID');await client.query("update personal_app_connections set status='active',upstream_id=$3,setup=null,state_hash=null,session_hash=null,expires_at=null,updated_at=now() where workspace_id=$1 and id=$2",[row.workspace_id,row.id,upstreamId]);await this.audit(client,context,row,'connected');});
  }catch(error){if(upstreamId)await engine.disconnect(upstreamId).catch(()=>{});await this.tx(context,async client=>{await client.query("update personal_app_connections set status='reconnect_required',setup=null,state_hash=null,session_hash=null,expires_at=null,updated_at=now() where workspace_id=$1 and id=$2 and generation=$3 and status='pending'",[row.workspace_id,row.id,row.generation]);}).catch(()=>{});throw error;}
 }
 async callback(context:AuthenticatedContext,session:string,raw:unknown){const body=parse(z.object({code:z.string().min(1).max(4096),state:z.string().regex(/^[A-Za-z0-9_-]{43}$/u)}).strict(),raw);
  const {row,value}=await this.tx(context,async client=>{const row=(await client.query<Row>("select * from personal_app_connections where workspace_id=$1 and owner_principal_id=$2 and state_hash=$3 and status='pending' for update",[context.membership.workspaceId,context.membership.principalId,hash(body.state)])).rows[0];if(!row||row.session_hash!==hash(session)||!row.expires_at||row.expires_at.getTime()<=Date.now()||context.membership.principalKind!=='human')fail('CONNECT_STATE_INVALID');const value=unseal<Record<string,unknown>>(this.encryption(),row.setup,this.aad(row));await client.query('update personal_app_connections set setup=null,state_hash=null,session_hash=null where workspace_id=$1 and id=$2',[row.workspace_id,row.id]);return {row,value};});
  const piece=await this.configured().metadata(row.app_id),central=this.configured().config.oauthClients[piece.name];if(!central)fail('PROVIDER_SETUP_REQUIRED',503);if(piece.version!==row.connector_version)fail('CONNECTOR_VERSION_UNAVAILABLE',409);await this.finish(context,row,piece,{...value,client_id:central.clientId,client_secret:central.clientSecret,code:body.code});return {appId:row.app_id,status:'connected'};
 }
 async disconnect(context:AuthenticatedContext,id:string){const row=await this.tx(context,async client=>{const row=await this.own(client,context,id);await client.query("update personal_app_connections set status='revoked',generation=generation+1,setup=null,state_hash=null,session_hash=null,expires_at=null,updated_at=now() where workspace_id=$1 and id=$2",[row.workspace_id,row.id]);await this.audit(client,context,row,'disconnected');return row;});if(row.upstream_id)await this.configured().disconnect(row.upstream_id);}
 private async bind(context:AuthenticatedContext,id:string,name:string,bound?:Bound):Promise<Bound>{return this.tx(context,async client=>{
  const row=(await client.query<Row>(`select c.* from personal_app_connections c join principals p on p.workspace_id=c.workspace_id and p.id=c.owner_principal_id join workspace_memberships m on m.workspace_id=p.workspace_id and m.principal_id=p.id where c.workspace_id=$1 and c.id=$2 and p.active and m.active`,[context.membership.workspaceId,parse(uuid,id)])).rows[0];if(!row||row.status!=='active'||!row.upstream_id)fail('FORBIDDEN',403);
  if(bound&&(bound.row.generation!==row.generation||bound.row.connector_version!==row.connector_version))fail('CONNECTION_INACTIVE',403);
  if(row.owner_principal_id===context.membership.principalId&&context.membership.principalKind==='human'&&(!bound||bound.grantId===null))return {row,actionName:name,grantId:null};
  const grant=(await client.query<{id:string}>(`select id from personal_action_grants where workspace_id=$1 and connection_id=$2 and recipient_principal_id=$3 and action_name=$4 and generation=$5 and connector_version=$6 and revoked_at is null and expires_at>now() and ($7::uuid is null or id=$7) order by created_at,id limit 1`,[row.workspace_id,row.id,context.membership.principalId,name,row.generation,row.connector_version,bound?.grantId??null])).rows[0];if(!grant)fail('FORBIDDEN',403);return {row,actionName:name,grantId:grant.id};
 });}
 async actions(context:AuthenticatedContext,id:string){const name=parse(uuid,id);const listed=await this.list(context),connection=listed.find(c=>c.id===name&&c.status==='active');if(!connection)fail('NOT_FOUND',404);
  const description=await this.describe(context,connection.appId);const allowed=connection.personal?description.actions:await this.tx(context,async client=>{const names=(await client.query<{action_name:string}>('select g.action_name from personal_action_grants g join personal_app_connections c on c.workspace_id=g.workspace_id and c.id=g.connection_id where g.workspace_id=$1 and g.connection_id=$2 and g.recipient_principal_id=$3 and g.generation=c.generation and g.connector_version=c.connector_version and g.revoked_at is null and g.expires_at>now()',[context.membership.workspaceId,id,context.membership.principalId])).rows.map(g=>g.action_name);return description.actions.filter(a=>names.includes(a.name));});return {connection,actions:allowed};
 }
 async fields(context:AuthenticatedContext,id:string,name:string,raw:unknown){parse(actionName,name);const input=literalInput(raw),bound=await this.bind(context,id,name);const engine=this.configured(),piece=await engine.metadata(bound.row.app_id);if(!Object.hasOwn(piece.actions,name)||piece.version!==bound.row.connector_version)fail('NOT_FOUND',404);await this.bind(context,id,name,bound);
  const fields=await engine.fields(piece,name,input,bound.row.external_id,()=>this.bind(context,id,name,bound));await this.bind(context,id,name,bound);return {fields:pieceFields(fields)};
 }
 async run(context:AuthenticatedContext,id:string,name:string,raw:unknown){parse(actionName,name);const input=literalInput(raw),bound=await this.bind(context,id,name);const engine=this.configured(),piece=await engine.metadata(bound.row.app_id);if(!Object.hasOwn(piece.actions,name))fail('NOT_FOUND',404);if(piece.version!==bound.row.connector_version)fail('CONNECTOR_VERSION_UNAVAILABLE',409);
  await this.bind(context,id,name,bound);await this.tx(context,client=>this.audit(client,context,bound.row,'run_started',name,bound.grantId));
  try{const result=await engine.runAction(piece,name,input,bound.row.external_id,()=>this.bind(context,id,name,bound));await this.bind(context,id,name,bound);await this.tx(context,client=>this.audit(client,context,bound.row,'run_succeeded',name,bound.grantId));await this.bind(context,id,name,bound);return {result:{content:result.content,structuredContent:null}};}catch(error){await this.tx(context,client=>this.audit(client,context,bound.row,'run_failed',name,bound.grantId)).catch(()=>{});throw error;}
 }
 async sharing(context:AuthenticatedContext,id:string){return this.tx(context,async client=>{await this.own(client,context,id);const recipients=(await client.query('select p.id,p.display_name as name,p.kind from principals p join workspace_memberships m on m.workspace_id=p.workspace_id and m.principal_id=p.id where p.workspace_id=$1 and p.active and m.active order by p.display_name limit 200',[context.membership.workspaceId])).rows;const grants=(await client.query('select id,recipient_principal_id as "recipientId",action_name as "actionName",expires_at as "expiresAt",revoked_at as "revokedAt" from personal_action_grants where workspace_id=$1 and connection_id=$2 order by created_at desc limit 200',[context.membership.workspaceId,id])).rows;return {recipients,grants};});}
 async grant(context:AuthenticatedContext,id:string,raw:unknown){const body=parse(z.object({recipientId:uuid,actionName,expiresAt:z.iso.datetime({offset:true}).refine(v=>Date.parse(v)>Date.now()+1000&&Date.parse(v)<=Date.now()+365*86400000)}).strict(),raw);const listed=await this.actions(context,id);if(!listed.connection.personal||!canShare(listed.connection.appId,body.actionName,listed.connection.version)||!listed.actions.some(a=>a.name===body.actionName))fail('FORBIDDEN',403);
  return this.tx(context,async client=>{const row=await this.own(client,context,id);if(row.status!=='active')fail('CONNECTION_INACTIVE',403);if(!(await client.query('select p.id from principals p join workspace_memberships m on m.workspace_id=p.workspace_id and m.principal_id=p.id where p.workspace_id=$1 and p.id=$2 and p.active and m.active',[row.workspace_id,body.recipientId])).rowCount)fail('NOT_FOUND',404);const grant=(await client.query<{id:string}>('insert into personal_action_grants(workspace_id,connection_id,grantor_principal_id,recipient_principal_id,action_name,generation,connector_version,expires_at) values($1,$2,$3,$4,$5,$6,$7,$8) returning id',[row.workspace_id,row.id,row.owner_principal_id,body.recipientId,body.actionName,row.generation,row.connector_version,body.expiresAt])).rows[0];await this.audit(client,context,row,'grant_created',body.actionName,grant?.id??null);return {id:grant?.id};});
 }
 async revoke(context:AuthenticatedContext,id:string,grantId:string){parse(uuid,grantId);await this.tx(context,async client=>{const row=await this.own(client,context,id);await client.query('update personal_action_grants set revoked_at=now() where workspace_id=$1 and connection_id=$2 and id=$3 and grantor_principal_id=$4',[row.workspace_id,id,grantId,context.membership.principalId]);await this.audit(client,context,row,'grant_revoked',null,grantId);});}
}
