import React,{useEffect,useRef,useState} from 'react';
import {sessionFetch,writeRequest} from './session.js';
const h=React.createElement;
export interface Action {id:string;app:'github'|'google-drive';name:string;description:string;fields:{key:string;name:string;description:string;required:boolean;type:'text'|'number'}[];connections:{id:string;name:string;repositories:{id:string;name:string}[]}[];}
export const actionErrors:Record<string,string>={INVALID_REQUEST:'Check the inputs. File and folder fields accept a Google Drive link or ID. Search names cannot contain quotes or backslashes.',FORBIDDEN:'You do not have current access to this action. Ask your workspace owner for an action grant.',CONNECTION_INACTIVE:'This connection changed. Reconnect it, then renew any action grants.',NOT_FOUND:'This action or connection is no longer available. Refresh actions.',CONNECTOR_BUSY:'Two actions are already running. Try again shortly.',CONNECTOR_TIMEOUT:'The action took too long. Try again.',PROVIDER_RESOURCE_NOT_FOUND:'The file or issue was not found, or the connected account cannot access it.',PROVIDER_AUTHORIZATION_EXPIRED:'Google access expired. Reconnect Google Drive.',PROVIDER_SCOPE_REQUIRED:'The connected account did not grant the required permission.',PROVIDER_REQUEST_FAILED:'The app could not complete the request. Check access and try again.',CONNECTOR_FAILED:'The app returned a result Capykit could not safely read. Try a narrower search.',CSRF_REQUIRED:'Reload Capykit to refresh your session, then try again.'};
export async function actionJson<T>(response:Response,expired:()=>void):Promise<T> {if(response.status===401){expired();throw new Error('Your session expired. Sign in again.');}if(!response.ok){const body=await response.json() as {error?:{code?:string}};throw new Error(actionErrors[body.error?.code??'']??'Capykit could not complete this request. Try again.');}return response.status===204?undefined as T:await response.json() as T;}
function driveId(value:string):string {try{const url=new URL(value);if(url.protocol==='https:'&&['drive.google.com','docs.google.com'].includes(url.hostname)){return url.pathname.match(/\/(?:d|folders)\/([A-Za-z0-9_-]+)/u)?.[1]??url.searchParams.get('id')??value;}}catch{/* An ordinary file ID is expected. */}return value.trim();}
export function ActionConsole({app,onSessionExpired}:{app?:'github'|'google-drive';onSessionExpired:()=>void}):React.ReactElement {
 const [catalog,setCatalog]=useState<Action[]|null>(null),[selected,setSelected]=useState(''),[connectionId,setConnectionId]=useState(''),[values,setValues]=useState<Record<string,string>>({});
 const [result,setResult]=useState<Record<string,unknown>|null>(null),[lastInput,setLastInput]=useState<Record<string,unknown>>({}),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const heading=useRef<HTMLHeadingElement>(null),epoch=useRef(0);
 const action=catalog?.find(a=>a.id===selected);const connection=action?.connections.find(c=>c.id===connectionId);
 async function refresh(){setError('');try{const data=await actionJson<{actions:Action[]}>(await sessionFetch('/v1/actions'),onSessionExpired);setCatalog(data.actions.filter(a=>!app||a.app===app));}catch(error){setError(error instanceof Error?error.message:'Could not load actions.');}}
 useEffect(()=>{void refresh();return()=>{epoch.current++;};},[app]);
 function choose(action:Action|undefined){epoch.current++;setSelected(action?.id??'');setConnectionId(action?.connections.length===1?action.connections[0]?.id??'':'');setValues({});setError('');setResult(null);setBusy(false);requestAnimationFrame(()=>heading.current?.focus());}
 async function run(input:Record<string,unknown>){if(!action||busy)return;const current=epoch.current;setBusy(true);setError('');setResult(null);try{const data=await actionJson<{result:Record<string,unknown>}>(await writeRequest(`/v1/actions/${encodeURIComponent(action.id)}/run`,'POST',{connectionId,input}),onSessionExpired);if(current===epoch.current){setResult(data.result);setLastInput(input);}}catch(error){if(current===epoch.current)setError(error instanceof Error?error.message:'Could not run action.');}finally{if(current===epoch.current)setBusy(false);}}
 function submit(event:React.SubmitEvent<HTMLElement>){event.preventDefault();if(!action)return;const input:Record<string,unknown>={};for(const field of action.fields){const value=values[field.key]?.trim();if(value)input[field.key]=field.type==='number'?Number(value):field.key==='fileId'||field.key==='folderId'?driveId(value):value;}if(action.app==='github')input.repositoryId=values.repositoryId;void run(input);}
 const files=Array.isArray(result?.files)?result.files as {id:string;name:string;mimeType:string}[]:null;
 return h('section',{className:'panel connector-actions','aria-label':'Available actions','aria-busy':busy},
  h('div',{className:'section-heading'},h('div',null,h('h2',{ref:heading,tabIndex:-1},action?action.name:'Available actions'),h('p',{className:'small muted'},action?'Read-only. Your files and issues will stay unchanged.':'Choose what you want to do with your connected app.')),h('button',{type:'button',className:'text-button',disabled:busy,onClick:()=>{void refresh();}},'Refresh actions')),
  error?h('p',{className:'message error',role:'alert'},error):null,
  catalog===null?h('p',{role:'status'},error?'Refresh actions to try again.':'Loading actions…'):catalog.length===0?h('p',{className:'muted'},'No actions are available. Connect an app or ask your workspace owner for access.'):!action?h('ul',{className:'action-list'},...catalog.map(a=>h('li',{key:a.id},h('button',{type:'button',className:'action-row',onClick:()=>{choose(a);}},h('span',null,h('strong',null,a.name),h('span',{className:'small muted'},a.app==='github'?'Read an issue from an approved repository.':a.id==='drive.get-file.v1'?'Read a file’s name, ID and type.':a.id==='drive.find-files.v1'?'Find files and folders by name.':'List file names inside a folder.')),h('span',{'aria-hidden':true},'›'))))):h(React.Fragment,null,
   h('button',{type:'button',className:'text-button connection-back',disabled:busy,onClick:()=>{choose(undefined);}},'← All actions'),
   h('form',{onSubmit:submit},
    h('label',null,'Connected account',h('select',{'aria-label':'Connected account',required:true,value:connectionId,disabled:busy,onChange:(event:React.ChangeEvent<HTMLSelectElement>)=>{setConnectionId(event.currentTarget.value);setValues({});setResult(null);}},h('option',{value:''},'Choose an account'),...action.connections.map(c=>h('option',{key:c.id,value:c.id},c.name)))),
    action.app==='github'?h('label',null,'Repository',h('select',{'aria-label':'Repository',required:true,value:values.repositoryId??'',disabled:busy||!connection,onChange:(event:React.ChangeEvent<HTMLSelectElement>)=>{const value=event.currentTarget.value;setValues(v=>({...v,repositoryId:value}));setResult(null);}},h('option',{value:''},'Choose a repository'),...connection?.repositories.map(r=>h('option',{key:r.id,value:r.id},r.name))??[])):null,
    ...action.fields.map(field=>h('label',{key:field.key},field.key==='name'?'Name contains':field.name,h('input',{required:field.required,type:field.type==='number'?'number':'text',...(field.type==='number'?{min:1,step:1,inputMode:'numeric' as const}:{}),maxLength:field.key==='name'?120:2048,value:values[field.key]??'',disabled:busy,onChange:event=>{const value=event.currentTarget.value;setValues(v=>({...v,[field.key]:value}));setResult(null);},placeholder:field.key==='name'?'e.g. Quarterly report':field.key==='folderId'?'Paste a folder link or ID (root for My Drive)':field.key==='fileId'?'Paste a file link or ID':'e.g. 12'}),field.key==='folderId'&&!field.required?h('span',{className:'small muted'},'Optional: search within this folder.'):null)),
    h('button',{type:'submit',disabled:busy||!connectionId},busy?'Running…':'Run action')),
   result?h('div',{className:'action-result',role:'status'},h('h3',null,'Action completed'),files?h(React.Fragment,null,files.length===0?h('p',null,'No matching files found.'):h('ul',{className:'action-files'},...files.map((file,index)=>h('li',{key:`${file.id}-${String(index)}`},h('a',{href:`https://drive.google.com/${file.mimeType==='application/vnd.google-apps.folder'?'drive/folders':'file/d'}/${encodeURIComponent(file.id)}`,target:'_blank',rel:'noopener noreferrer'},file.name),h('span',{className:'small muted'},file.mimeType==='application/vnd.google-apps.folder'?'Folder':file.mimeType),h('span',{className:'small file-id'},file.id)))),typeof result.nextPageToken==='string'?h('button',{type:'button',className:'secondary',disabled:busy,onClick:()=>{void run({...lastInput,pageToken:result.nextPageToken});}},'Next 25 results'):null):h('dl',null,...Object.entries(result).flatMap(([key,value])=>[h('dt',{key:`${key}-label`},key),h('dd',{key},String(value))]))):null));
}
