import React,{useEffect,useState} from 'react';
import {sessionFetch,writeRequest} from './session.js';
import {actionJson,type Action} from './actions.js';
const h=React.createElement;
interface AccessOptions {actions:Action[];recipients:{id:string;name:string;kind:string}[];keys:{id:string;principalId:string;name:string;expiresAt:string;status:string}[];grants:{id:string;name:string;actionId:string;connectionId:string;repositoryIds:string[];expiresAt:string;status:string}[];}
function defaultExpiry(){const d=new Date(Date.now()+30*86400000);d.setMinutes(d.getMinutes()-d.getTimezoneOffset());return d.toISOString().slice(0,16);}
export function ActionAccess({active,onSessionExpired}:{active:boolean;onSessionExpired:()=>void}):React.ReactElement {
 const [data,setData]=useState<AccessOptions|null>(null),[name,setName]=useState(''),[expires,setExpires]=useState(defaultExpiry),[key,setKey]=useState<string|null>(null);
 const [recipientId,setRecipientId]=useState(''),[actionId,setActionId]=useState(''),[connectionId,setConnectionId]=useState(''),[repositoryIds,setRepositoryIds]=useState<string[]>([]);
 const [busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[confirm,setConfirm]=useState<{kind:'key'|'grant'|'rotate';id:string}|null>(null);
 const action=data?.actions.find(a=>a.id===actionId),connection=action?.connections.find(c=>c.id===connectionId);
 async function refresh(){const value=await actionJson<AccessOptions>(await sessionFetch('/v1/action-access'),onSessionExpired);setData(value);}
 useEffect(()=>{if(active)void refresh().catch((error:unknown)=>{setError(error instanceof Error?error.message:'Could not load action access.');});},[active]);
 async function mutate(run:()=>Promise<void>){setBusy(true);setError('');setNotice('');try{await run();await refresh();}catch(error){setError(error instanceof Error?error.message:'Could not update action access.');}finally{setBusy(false);}}
 async function issue(event:React.SubmitEvent<HTMLElement>){event.preventDefault();await mutate(async()=>{const value=await actionJson<{key:string;principalId:string}>(await writeRequest('/v1/agents/keys','POST',{name,expiresAt:new Date(expires).toISOString()}),onSessionExpired);setKey(value.key);setRecipientId(value.principalId);setName('');setNotice('Agent created. Grant an action below before it can do any work.');});}
 async function grant(event:React.SubmitEvent<HTMLElement>){event.preventDefault();await mutate(async()=>{await actionJson(await writeRequest('/v1/action-grants','POST',{recipientId,actionId,connectionId,repositoryIds,expiresAt:new Date(expires).toISOString()}),onSessionExpired);setNotice('Action access granted. Reconnecting the app will require a new grant.');});}
 async function confirmed(){if(!confirm)return;const choice=confirm;await mutate(async()=>{if(choice.kind==='rotate'){const value=await actionJson<{key:string}>(await writeRequest('/v1/agents/keys','POST',{rotateKeyId:choice.id,expiresAt:new Date(expires).toISOString()}),onSessionExpired);setKey(value.key);setNotice('The old key is revoked. Save the replacement key. Existing action grants remain unchanged.');}else{await actionJson(await writeRequest(choice.kind==='key'?`/v1/agents/keys/${choice.id}`:`/v1/action-grants/${choice.id}`,'DELETE'),onSessionExpired);setNotice('Access revoked. Future calls will be denied.');}setConfirm(null);});}
 return h('section',{className:'action-access','aria-label':'Connected-app access','aria-busy':busy},h('section',{className:'panel'},
  h('div',{className:'section-heading'},h('div',null,h('h2',null,'Connected-app access'),h('p',{className:'muted'},'Give people or agents access to specific app actions.')),h('button',{type:'button',className:'text-button',disabled:busy,onClick:()=>{void mutate(refresh);}},'Refresh action access')),
  error?h('p',{className:'message error',role:'alert'},error):null,notice?h('p',{className:'message success',role:'status'},notice):null,
  key?h('div',{className:'connection-consent',role:'status'},h('h3',null,'Save your agent key'),h('p',null,'This key is shown once. Store it in your agent’s secret environment variables.'),h('code',{className:'agent-key'},key),h('button',{type:'button',className:'secondary',onClick:()=>{setKey(null);}},'I saved the key')):null,
  h('h3',null,'Create an agent'),h('form',{onSubmit:event=>{void issue(event);}},h('label',null,'Agent name',h('input',{required:true,maxLength:80,value:name,disabled:busy||key!==null,onChange:event=>{setName(event.currentTarget.value);},placeholder:'e.g. Research assistant'})),h('label',null,'Access expires',h('input',{type:'datetime-local',required:true,value:expires,disabled:busy,onChange:event=>{setExpires(event.currentTarget.value);}})),h('p',{className:'small muted'},'The default is 30 days. A key identifies the agent and grants no app access by itself.'),h('button',{type:'submit',disabled:busy||key!==null},'Create agent and key')),
  !data?null:h(React.Fragment,null,h('h3',null,'Grant an action'),data.actions.length===0?h('p',null,'Connect an app in Apps first.'):h('form',{onSubmit:event=>{void grant(event);}},
   h('label',null,'Recipient',h('select',{'aria-label':'Recipient',required:true,value:recipientId,disabled:busy,onChange:(event:React.ChangeEvent<HTMLSelectElement>)=>{setRecipientId(event.currentTarget.value);}},h('option',{value:''},'Choose a person or agent'),...data.recipients.map(r=>h('option',{key:r.id,value:r.id},`${r.name} · ${r.kind}`)))),
   h('label',null,'Action',h('select',{'aria-label':'Action',required:true,value:actionId,disabled:busy,onChange:(event:React.ChangeEvent<HTMLSelectElement>)=>{setActionId(event.currentTarget.value);setConnectionId('');setRepositoryIds([]);}},h('option',{value:''},'Choose an action'),...data.actions.map(a=>h('option',{key:a.id,value:a.id},`${a.app==='github'?'GitHub':'Google Drive'} · ${a.name}`)))),
   h('label',null,'Connected account',h('select',{'aria-label':'Connected account',required:true,value:connectionId,disabled:busy,onChange:(event:React.ChangeEvent<HTMLSelectElement>)=>{setConnectionId(event.currentTarget.value);setRepositoryIds([]);}},h('option',{value:''},'Choose an account'),...action?.connections.map(c=>h('option',{key:c.id,value:c.id},c.name))??[])),
   action?.app==='github'&&connection?h('fieldset',{className:'repository-picker',disabled:busy},h('legend',null,'Allowed repositories'),...connection.repositories.map(r=>h('label',{key:r.id,className:'checkbox-label'},h('input',{type:'checkbox',checked:repositoryIds.includes(r.id),onChange:event=>{const selected=event.currentTarget.checked;setRepositoryIds(ids=>selected?[...ids,r.id]:ids.filter(id=>id!==r.id));}}),r.name))):null,
   h('p',{className:'small muted'},`Expires ${new Date(expires).toLocaleString()}. ${action?.app==='google-drive'?'Allows this action across file metadata accessible to the connected Google account.':''} The recipient uses your connection without receiving its credentials.`),
   h('button',{type:'submit',disabled:busy||!recipientId||!actionId||!connectionId||(action?.app==='github'&&repositoryIds.length===0)},'Grant action access')),
   h('h3',null,'Agent keys'),data.keys.length===0?h('p',{className:'muted'},'No agent keys yet.'):data.keys.map(k=>h('article',{className:'published-version',key:k.id},h('strong',null,k.name),h('p',{className:'small muted'},`${k.status} · Expires ${new Date(k.expiresAt).toLocaleString()}`),k.status==='revoked'?null:h('div',{className:'actions'},h('button',{type:'button',className:'secondary',disabled:busy,onClick:()=>{setConfirm({kind:'rotate',id:k.id});}},'Rotate key'),h('button',{type:'button',className:'text-button danger-text',disabled:busy,onClick:()=>{setConfirm({kind:'key',id:k.id});}},'Revoke key')))),
   h('h3',null,'Action grants'),data.grants.length===0?h('p',{className:'muted'},'No action grants yet.'):data.grants.map(g=>h('article',{className:'published-version',key:g.id},h('strong',null,`${g.name} · ${data.actions.find(a=>a.id===g.actionId)?.name??g.actionId}`),h('p',{className:'small muted'},`${g.status} · ${g.repositoryIds.length?`${String(g.repositoryIds.length)} repositories · `:''}Expires ${new Date(g.expiresAt).toLocaleString()}`),g.status==='revoked'?null:h('button',{type:'button',className:'text-button danger-text',disabled:busy,onClick:()=>{setConfirm({kind:'grant',id:g.id});}},'Revoke action access'))),
   h('p',{className:'small muted'},'Showing up to 200 recipients, keys and grants. Published function and skill grants above remain separate.')),
  confirm?h('div',{className:'connection-confirm'},h('p',null,confirm.kind==='rotate'?'Replace this key? The old key will stop working immediately.':confirm.kind==='key'?'Revoke this key? The agent will no longer authenticate with it.':'Revoke this action grant? Future calls will be denied.'),h('div',{className:'actions'},h('button',{type:'button',className:'danger',disabled:busy,onClick:()=>{void confirmed();}},confirm.kind==='rotate'?'Confirm rotation':'Confirm revoke'),h('button',{type:'button',className:'secondary',disabled:busy,onClick:()=>{setConfirm(null);}},'Cancel'))):null,
  h('details',null,h('summary',null,'Connect an agent from another environment'),h('p',null,'Set CAPYKIT_BASE_URL to this deployment’s HTTPS origin and CAPYKIT_API_KEY to the saved key. Start capykit-mcp --remote. The agent can discover and run only its granted actions. Provider credentials stay in Capykit.'))));
}
