import React,{useEffect,useRef,useState} from 'react';
import type { PieceField } from '../hosted/piece-properties.js';
import { sessionFetch,writeRequest } from './session.js';
const h=React.createElement;
export interface PersonalAccount {id:string;appId:string;name:string;status:string;personal:boolean;version:string;}
interface Method {index:number;type:string;name:string;description:string;fields:PieceField[];ready:boolean;scopes?:string[];}
interface Action {name:string;displayName:string;description:string;shareable?:boolean;fields:PieceField[];}
const messages:Record<string,string>={PROVIDER_SETUP_REQUIRED:'Capykit needs to finish provider setup before sign-in is available. You do not need developer credentials.',PROVIDER_CREDENTIALS_INVALID:'The provider could not verify these credentials. Check them and try again.',CONNECTOR_VERSION_UNAVAILABLE:'This connector needs an update by Capykit. Your saved account is unchanged.',FORBIDDEN:'You no longer have permission to use this account or action.',CONNECTION_INACTIVE:'This connection changed. Refresh and reconnect if needed.',CONNECT_STATE_INVALID:'This setup expired or was already used. Connect again.',CONNECTOR_BUSY:'Capykit is busy. Try again shortly.',PROVIDER_REQUEST_FAILED:'The provider could not complete this request. Check the inputs and account permissions. An action may have started; check the app before retrying.',INVALID_REQUEST:'Check the inputs. Template expressions are not supported.',CONFIGURATION_UNAVAILABLE:'Connections are temporarily unavailable. Please try again later.'};
export async function personalJson<T>(response:Response,expired:()=>void):Promise<T>{if(response.status===401){expired();throw new Error('Sign in again to continue.');}if(!response.ok){const value=await response.json() as {error?:{code?:string}};throw new Error(messages[value.error?.code??'']??'Capykit could not complete this request. Please try again.');}return response.status===204?undefined as T:await response.json() as T;}
function fieldValue(field:PieceField,value:string):unknown {if(field.type==='CHECKBOX')return value==='true';if(field.type==='NUMBER')return Number(value);if(field.options){const option=field.options.find(o=>JSON.stringify(o.value)===value);return option?option.value:value;}if(['OBJECT','JSON','DYNAMIC'].includes(field.type))return JSON.parse(value);if(field.type==='ARRAY'||field.type.includes('MULTI_SELECT'))return value.trim().startsWith('[')?JSON.parse(value):value.split('\n').map(v=>v.trim()).filter(Boolean);return value;}
function inputs(fields:PieceField[],values:Record<string,string>){return Object.fromEntries(fields.flatMap(field=>{const value=values[field.key];return value===undefined||value===''?[]:[[field.key,fieldValue(field,value)]];}));}
function initial(fields:PieceField[]){return Object.fromEntries(fields.filter(f=>f.defaultValue!==undefined).map(f=>[f.key,typeof f.defaultValue==='string'?f.defaultValue:JSON.stringify(f.defaultValue)]));}
function Fields({fields,values,setValues,disabled,credentials=false}:{fields:PieceField[];values:Record<string,string>;setValues:React.Dispatch<React.SetStateAction<Record<string,string>>>;disabled:boolean;credentials?:boolean}){
 return h(React.Fragment,null,...fields.filter(f=>f.type!=='MARKDOWN').map(field=>{const value=values[field.key]??'',change=(next:string)=>{setValues(v=>({...v,[field.key]:next}));};const secret=credentials&&field.secret;
  return h('label',{key:field.key},field.name,field.type==='CHECKBOX'?h('input',{type:'checkbox',checked:value==='true',disabled,onChange:event=>{change(String(event.currentTarget.checked));}}):field.options&&field.options.length&&!field.type.includes('MULTI_SELECT')?h('select',{required:field.required,value,disabled,onChange:(event:React.ChangeEvent<HTMLSelectElement>)=>{change(event.currentTarget.value);}},h('option',{value:''},'Choose an option'),...field.options.map((o,index)=>h('option',{key:index,value:JSON.stringify(o.value)},o.label))):!secret&&['LONG_TEXT','RICH_TEXT','JSON','OBJECT','DYNAMIC','ARRAY','STATIC_MULTI_SELECT_DROPDOWN','MULTI_SELECT_DROPDOWN'].includes(field.type)?h('textarea',{required:field.required,value,disabled,rows:4,maxLength:16000,onChange:(event:React.ChangeEvent<HTMLTextAreaElement>)=>{change(event.currentTarget.value);},placeholder:field.type==='ARRAY'||field.type.includes('MULTI_SELECT')?'One value per line':field.type==='OBJECT'||field.type==='JSON'||field.type==='DYNAMIC'?'{}':undefined}):h('input',{type:secret?'password':field.type==='NUMBER'?'number':'text',required:field.required,disabled,value,maxLength:16000,autoComplete:secret?'off':undefined,spellCheck:!secret,onChange:event=>{change(event.currentTarget.value);}}),field.description?h('span',{className:'small muted'},field.description):null);
 }));
}
export function PersonalApp({appId,appName,accounts,onSessionExpired,onChanged}:{appId:string;appName:string;accounts:PersonalAccount[];onSessionExpired:()=>void;onChanged:()=>void}){
 const [schema,setSchema]=useState<{methods:Method[]}|null>(null),[methodIndex,setMethodIndex]=useState(0),[name,setName]=useState(`My ${appName}`),[credentials,setCredentials]=useState<Record<string,string>>({});
 const [error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[adding,setAdding]=useState(accounts.every(a=>a.status!=='active'));
 const [accountId,setAccountId]=useState(accounts.find(a=>a.status==='active')?.id??''),[actions,setActions]=useState<Action[]>([]),[actionName,setActionName]=useState(''),[fields,setFields]=useState<PieceField[]>([]),[values,setValues]=useState<Record<string,string>>({}),[result,setResult]=useState<unknown>(null),[disconnecting,setDisconnecting]=useState(false);
 const [sharing,setSharing]=useState<{recipients:{id:string;name:string;kind:string}[];grants:{id:string;recipientId:string;actionName:string;expiresAt:string;revokedAt:string|null}[]}|null>(null),[recipient,setRecipient]=useState(''),[shareAction,setShareAction]=useState('');const epoch=useRef(0);
 const account=accounts.find(a=>a.id===accountId),method=schema?.methods.find(m=>m.index===methodIndex),action=actions.find(a=>a.name===actionName);
 async function request<T>(path:string){return personalJson<T>(await sessionFetch(path),onSessionExpired);}
 useEffect(()=>{let live=true;void request<{methods:Method[]}>(`/v1/apps/${encodeURIComponent(appId)}/connection-schema`).then(v=>{if(live)setSchema(v);}).catch((e:unknown)=>{if(live)setError(e instanceof Error?e.message:'Could not load connection options.');});return()=>{live=false;epoch.current++;};},[appId]);
 useEffect(()=>{let live=true;setActions([]);setActionName('');setResult(null);setSharing(null);if(account?.status==='active')void request<{actions:Action[]}>(`/v1/connections/personal/${accountId}/actions`).then(v=>{if(live)setActions(v.actions);}).catch((e:unknown)=>{if(live)setError(e instanceof Error?e.message:'Could not load actions.');});return()=>{live=false;epoch.current++;};},[accountId,account?.status]);
 async function connect(event:React.SubmitEvent<HTMLFormElement>){event.preventDefault();if(!method||busy)return;setBusy(true);setError('');try{const fields=method.type==='SECRET_TEXT'?[{key:'secret_text',name:'API key',type:'SECRET_TEXT',required:true,secret:true,description:''}]:method.type==='BASIC_AUTH'?[{key:'username',name:'Username',type:'SHORT_TEXT',required:true,secret:false,description:''},{key:'password',name:'Password',type:'SECRET_TEXT',required:true,secret:true,description:''}]:method.fields;
  const current=epoch.current;const value=await personalJson<{authorizationUrl?:string;connectionId:string}>(await writeRequest(`/v1/apps/${encodeURIComponent(appId)}/connect`,'POST',{name,method:methodIndex,credentials:inputs(fields,credentials)}),onSessionExpired);if(current!==epoch.current)return;setCredentials({});
  if(value.authorizationUrl){const url=new URL(value.authorizationUrl);if(url.protocol!=='https:'||url.username||url.password)throw new Error('Invalid provider authorization address.');sessionStorage.setItem('capykit_personal_app',appId);sessionStorage.setItem('capykit_personal_state',url.searchParams.get('state')??'');window.location.assign(url.href);return;}
  setNotice(`${appName} is connected. Only you can use it until you share an action.`);setAccountId(value.connectionId);setAdding(false);onChanged();
 }catch(e){setError(e instanceof Error?e.message:'Could not connect.');}finally{setBusy(false);}}
 async function choose(name:string){const current=++epoch.current;setActionName(name);setError('');setResult(null);const a=actions.find(a=>a.name===name);setFields(a?.fields??[]);setValues(initial(a?.fields??[]));if(!a)return;setBusy(true);try{const data=await personalJson<{fields:PieceField[]}>(await writeRequest(`/v1/connections/personal/${accountId}/actions/${encodeURIComponent(name)}/fields`,'POST',{input:{}}),onSessionExpired);if(current===epoch.current&&data.fields.length){setFields(data.fields);setValues(initial(data.fields));}}catch(e){if(current===epoch.current)setError(e instanceof Error?e.message:'Could not load account options.');}finally{if(current===epoch.current)setBusy(false);}}
 async function run(event:React.SubmitEvent<HTMLFormElement>){event.preventDefault();if(!action||busy)return;setBusy(true);setError('');setResult(null);const current=epoch.current;try{const value=await personalJson<{result:unknown}>(await writeRequest(`/v1/connections/personal/${accountId}/actions/${encodeURIComponent(action.name)}/run`,'POST',{input:inputs(fields,values)}),onSessionExpired);if(current===epoch.current)setResult(value.result);}catch(e){if(current===epoch.current)setError(e instanceof Error?e.message:'Could not run action.');}finally{if(current===epoch.current)setBusy(false);}}
 async function disconnect(){if(busy)return;setBusy(true);setError('');try{await personalJson(await writeRequest(`/v1/connections/personal/${accountId}`,'DELETE'),onSessionExpired);setDisconnecting(false);setActions([]);setActionName('');setResult(null);setAccountId('');setNotice('This account is disconnected and its shared actions can no longer be used.');setAdding(true);onChanged();}catch(e){setError(e instanceof Error?e.message:'Could not disconnect.');onChanged();}finally{setBusy(false);}}
 async function loadSharing(){setError('');try{setSharing(await request(`/v1/connections/personal/${accountId}/sharing`));}catch(e){setError(e instanceof Error?e.message:'Could not load sharing.');}}
 async function share(event:React.SubmitEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setError('');try{await personalJson(await writeRequest(`/v1/connections/personal/${accountId}/grants`,'POST',{recipientId:recipient,actionName:shareAction,expiresAt:new Date(Date.now()+30*86400000).toISOString()}),onSessionExpired);setNotice('This action is shared for 30 days. All other actions remain private.');await loadSharing();}catch(e){setError(e instanceof Error?e.message:'Could not share action.');}finally{setBusy(false);}}
 async function revoke(id:string){setBusy(true);setError('');try{await personalJson(await writeRequest(`/v1/connections/personal/${accountId}/grants/${id}`,'DELETE'),onSessionExpired);await loadSharing();setNotice('Action access revoked.');}catch(e){setError(e instanceof Error?e.message:'Could not revoke access.');}finally{setBusy(false);}}
 useEffect(()=>{if(method)setCredentials(initial(method.fields));},[schema,methodIndex]);
 const authFields:PieceField[]=method?.type==='SECRET_TEXT'?[{key:'secret_text',name:'API key',required:true,type:'SECRET_TEXT',secret:true,description:''}]:method?.type==='BASIC_AUTH'?[{key:'username',name:'Username',required:true,type:'SHORT_TEXT',secret:false,description:''},{key:'password',name:'Password',required:true,type:'SECRET_TEXT',secret:true,description:''}]:method?.fields??[];
 return h('section',{className:'panel personal-app','aria-label':`${appName} personal connections`,'aria-busy':busy},h('h2',null,accounts.length?'Your accounts':`Connect ${appName}`),h('p',{className:'muted'},'Personal by default. Only you can use your account until you share specific actions.'),error?h('p',{role:'alert',className:'message error'},error):null,notice?h('p',{role:'status',className:'message success'},notice):null,
  accounts.length?h('label',null,'Account',h('select',{value:accountId,disabled:busy,onChange:(event:React.ChangeEvent<HTMLSelectElement>)=>{epoch.current++;setBusy(false);setAccountId(event.currentTarget.value);setDisconnecting(false);}},h('option',{value:''},'Choose an account'),...accounts.filter(a=>a.status==='active').map(a=>h('option',{key:a.id,value:a.id},`${a.name}${a.personal?' · Personal':' · Shared with you'}`)))):null,
  !adding?h('button',{type:'button',className:'secondary',disabled:busy,onClick:()=>{setAdding(true);}},`Connect another ${appName} account`):schema?h('form',{onSubmit:connect},h('h3',null,`Connect ${appName}`),h('label',null,'Account name',h('input',{required:true,maxLength:80,value:name,disabled:busy,onChange:event=>{setName(event.currentTarget.value);}})),schema.methods.length>1?h('label',null,'Connection method',h('select',{value:methodIndex,disabled:busy,onChange:(event:React.ChangeEvent<HTMLSelectElement>)=>{setMethodIndex(Number(event.currentTarget.value));setCredentials({});setError('');}},...schema.methods.map(m=>h('option',{key:m.index,value:m.index},m.type==='OAUTH2'?'Sign in with the provider':m.type==='SECRET_TEXT'?'API key':m.type==='BASIC_AUTH'?'Username and password':m.name)))):null,
   method?.description?h('p',{className:'small muted'},method.description):null,method?.ready?h(React.Fragment,null,h(Fields,{fields:authFields,values:credentials,setValues:setCredentials,disabled:busy,credentials:true}),method.type==='OAUTH2'?h('details',null,h('summary',null,'Requested permissions'),h('p',{className:'small muted'},'The provider will show these permissions before you approve.'),h('ul',null,...method.scopes?.map(scope=>h('li',{key:scope},scope))??[])):null,h('button',{type:'submit',disabled:busy},busy?'Connecting…':method.type==='NO_AUTH'?`Enable ${appName}`:`Connect ${appName}`)):h('p',{className:'message',role:'status'},'Capykit needs to finish provider setup before sign-in is available. You do not need to create an OAuth client.'),accounts.length?h('button',{type:'button',className:'text-button',disabled:busy,onClick:()=>{setAdding(false);setCredentials({});}},'Cancel'):null):h('p',{role:'status'},'Loading connection options…'),
  account?.status==='active'?h(React.Fragment,null,h('hr'),h('h3',null,'Available actions'),h('p',{className:'small muted'},'Actions may read or change data in your connected app. Review the action and inputs before running.'),!action?h('ul',{className:'action-list'},...actions.map(a=>h('li',{key:a.name},h('button',{type:'button',className:'action-row',disabled:busy,onClick:()=>{void choose(a.name);}},h('span',null,h('strong',null,a.displayName),h('span',{className:'small muted'},a.description)),h('span',{'aria-hidden':true},'›'))))):h(React.Fragment,null,h('button',{type:'button',className:'text-button',disabled:busy,onClick:()=>{void choose('');}},'← All actions'),h('h3',null,action.displayName),h('form',{onSubmit:run},h(Fields,{fields,values,setValues,disabled:busy}),h('button',{type:'submit',disabled:busy},busy?'Loading or running…':'Run action')),result?h('div',{role:'status'},h('h3',null,'Action completed'),h('pre',null,JSON.stringify(result,null,2))):null),
   account.personal?h(React.Fragment,null,h('div',{className:'actions'},h('button',{type:'button',className:'secondary',disabled:busy,onClick:()=>{void loadSharing();}},'Share an action'),h('button',{type:'button',className:'text-button',disabled:busy,onClick:()=>{setDisconnecting(true);}},'Disconnect')),
    disconnecting?h('div',{className:'message'},h('p',null,'Disconnect this account? Existing shared actions will stop working.'),h('button',{type:'button',className:'danger',disabled:busy,onClick:()=>{void disconnect();}},'Confirm disconnect'),h('button',{type:'button',className:'secondary',disabled:busy,onClick:()=>{setDisconnecting(false);}},'Keep connected')):null,
    sharing?h('div',{className:'personal-sharing'},h('h3',null,'Share a specific action'),h('p',{className:'small muted'},'Recipients can use only the selected action for 30 days. Actions that can forward credentials are not available for sharing.'),h('form',{onSubmit:share},h('label',null,'User or agent',h('select',{required:true,value:recipient,disabled:busy,onChange:(event:React.ChangeEvent<HTMLSelectElement>)=>{setRecipient(event.currentTarget.value);}},h('option',{value:''},'Choose a recipient'),...sharing.recipients.map(r=>h('option',{key:r.id,value:r.id},`${r.name} · ${r.kind}`)))),h('label',null,'Action',h('select',{required:true,value:shareAction,disabled:busy,onChange:(event:React.ChangeEvent<HTMLSelectElement>)=>{setShareAction(event.currentTarget.value);}},h('option',{value:''},'Choose an action'),...actions.filter(a=>a.shareable).map(a=>h('option',{key:a.name,value:a.name},a.displayName)))),h('button',{type:'submit',disabled:busy},'Share action')),h('ul',null,...sharing.grants.filter(g=>!g.revokedAt).map(g=>h('li',{key:g.id},`${sharing.recipients.find(r=>r.id===g.recipientId)?.name??'Recipient'} · ${g.actionName} · expires ${new Date(g.expiresAt).toLocaleDateString()}`,h('button',{type:'button',className:'text-button',disabled:busy,onClick:()=>{void revoke(g.id);}},'Revoke access'))))):null):null):null);
}
